### PR TITLE
using a list element here instead?

### PR DESCRIPTION
**Pull request by skanyanga**
would look better

### CODE REVIEW

**Comment by timturner13** [comment]
yeah I see what you mean 
looks more professuioal
thanks again

**Comment by skanyanga** [comment]
i was thinking , have you thought about using css?

**Comment by timturner13** [comment]
yeah I thought about it
not sure though
what do you think ?

**Comment by skanyanga** [comment]
yessssss html is cool but css gives you that extra creativity , im very very rusty but ill do some research if you are up for a bit of research/ challenge?

**Comment by timturner13** [comment]
haha bring it on 
ill speak to u later in the week 
let me get my hands on some books first  :P

**Comment by skanyanga** [comment]
ok 👍

**Pull request merged**
